[project]
name = "project-template"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "hydra-core>=1.3.2",
    "lightning>=2.4.0",
    "neptune>=1.12.0",
    "rich>=13.9.2",
    "rootutils>=1.0.7",
    "wandb>=0.18.3",
]
