fix = true
show-fixes = true
line-length = 120
target-version = "py310"
extend-include = ["*.ipynb"]

[lint]
select = [
  "I",    # isort
  "F",    # Pyflakes
  "E",    # pycodestyle (errors)
  "W",    # pycodestyle (warnings)
  "N",    # pep8-naming
  "B",    # flake8-bugbear
  "A",    # flake8-builtins
  "D",    # pydocstyle
  "C4",   # flake8-comprehensions
  "PT",   # flake8-pytest-style
  "UP",   # pyupgrade
  "TID",  # flake8-tidy-imports
  "SIM",  # flake8-simplify
  "TCH",  # flake8-type-checking
  "FLY",  # flynt
  "TRY",  # tryceratops
  "NPY",  # NumPy-specific rules
  "C901", # Cognitive complexity
]
ignore = [
  "B023",   # allow using local variable in for-loops
]

extend-ignore = []

[lint.pydocstyle]
convention = "google"

[lint.mccabe]
max-complexity = 20

[lint.per-file-ignores]
"notebooks/*" = [
  "B018", # allow useless-expression in notebooks
]
