site_name: Machine Learning Project Template Documentation
site_description: Documentation
site_author: Rayan Samy Ramoul
# site_url: #TODO: Fill when deployment CI added
site_dir: ../public
repo_url: https://github.com/rayanramoul/ml-project-template
edit_uri: blob/main/docs/
docs_dir: .


theme:
  name: "material"
  features:
    - search.suggest
    - search.highlight
    - search.share
  icon:
    repo: fontawesome/brands/github
    language: en
  palette:
    - scheme: default
      primary: white
      accent: purple
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: lime
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  features:
    - navigation.tracking # the URL is automatically updated with the active anchor
    - navigation.sections # top-level sections are rendered as groups in the sidebar
    - navigation.tabs # horizontal tabs at the top of the page
    - navigation.tabs.sticky # navigation tabs will lock below the header and always remain visible when scrolling
    - navigation.indexes # documents can be directly attached to sections
    - search.highlight # highlight search result
    - search.share # share button
    - search.suggest # smart suggestion
    - toc.integrate
    - toc.follow
    - content.code.annotate
    - navigation.tabs
    - navigation.top

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
      emoji_index: !!python/name:pymdownx.emoji.gemoji
  - pymdownx.snippets:
      base_path: ../
  - pymdownx.pathconverter:
      base_path: ../
      relative_path: docs
  - toc:
      permalink: "#"
      toc_depth: 3
  - pymdownx.highlight:
      linenums: true
  - def_list
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid

plugins:
  - mkdocstrings:
      default_handler: python
      import:
        - https://docs.python-requests.org/en/master/objects.inv
      load_external_modules: true
      handlers:
        python:
          paths: [.., ../src]
  - gen-files:
      scripts:
        - ../scripts/gen_doc_stubs.py
  - search
  - same-dir
