name: Linting 🎨
on:
  push:
    branches: [main, master]
  pull_request:
    branches:
      - "**"
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10" # Explicitly specify Python 3.10
      - name: Install dependencies
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          uv sync --extra lint
      - name: Run pre-commit hooks
        run: |
          uv run --no-sync pre-commit run --all-files
